### PR TITLE
Migrate app to use angular-cli

### PR DESCRIPTION
**Pull request by belev**
@buren We are using the angular-cli now. The project structure is basically the same as the old one. All of the old configurations are removed (which in my opinion is good because we decrease the complexity). The angular-cli build supports tree shaking out of the box so the build will be optimized. The development build is also faster than before.

Properly use `font-awesome` and `bootstrap`.

When you and @bvangelov review the PR I suggest to merge it as soon as possible so that all of the work can be applied over the new changes.

### CODE REVIEW

**Comment by belev** [comment]
Also the PR contains some refinements:
- proper usage of font-awesome and bootstrap

**Comment by buren** [comment]
👑

**Comment by buren** [comment]
Closes https://github.com/justarrived/just-match-web/pull/77

**Comment by bvangelov** [comment]
@buren Do you have any remarks here? I really want to merge it and merge my current code changes :)

**Pull request merged**
