### PR TITLE
Error handling for profile picture uploading closes #197

### LINKED ISSUE #197: Profile image upload, LMA card and other file uploads are not working
**Comment:**
It is not possible to upload a profile image or the other work documents, at least not in lastest Chrome on OSX. 

image

image

**Update:**
I tried it again now and it seems to be working correctly now. It did not however during the test session, might there be some other problem here? Let's investigate this!

### PR DESCRIPTION
**Pull request by Ekman1991**

### CODE REVIEW

**Comment by Ekman1991** [comment]
screen shot 2017-02-02 at 16 46 33
screen shot 2017-02-02 at 16 46 18

**Comment by Ekman1991** [comment]
Do we want to implement a loading gif aswell?

**Comment by bex1** [comment]
This does not close the issue since the issue includes all image uploads in profile details aswell

**Comment by bex1** [comment]
There is a loading gif component that can be used

**Comment by bex1** [comment]
This has now been solved:
Loading gifs added.
Input disabled when uloading.
Restricted images that can be picked to those accepted by api.

**Pull request merged**
