### PR TITLE
Footer font

### PR DESCRIPTION
**Pull request by tikkat**
According to me the museo font makes the footer a little prettier haha, do you agree/disagree?

### CODE REVIEW

**Comment by tikkat** [comment]
image

With museo

**Comment by tikkat** [comment]
image

Without

**Comment by tikkat** [comment]
I know I'm not solving anything but first-world problems with this PR ;)

**Comment by bex1** [comment]
Looks sexy! Oh you god of fonts!

**Comment by buren** [comment]
👍 for this

👀 watch out for duplicate definitions of `$museo` when merging this, since `$museo` has already been merged to `develop` :)

**Comment by tikkat** [comment]
Thanks for the heads up @buren ! I did refactor museo in this PR, great that you're telling me but I have already thought about that :) merging now

**Comment by buren** [comment]
@tikkat :crown:

**Pull request merged**
